#
#   This .bashrc part is dedicated to the management of your MultiversX API Services 
#

# Import necessary scripts
source $HOME/mvx-api-deployer/config.cfg
source $HOME/mvx-api-deployer/scripts/0-common.sh
source $HOME/mvx-api-deployer/scripts/5-manage-services.sh

#------------------------------------------------------------
#                Service Status Commands
#------------------------------------------------------------

api_check_status() {
    Check_All_Status
}

#------------------------------------------------------------
#                Observing Squad Commands
#------------------------------------------------------------

api_obssquad_start() {
    ObsSquad_Start
}

api_obssquad_stop() {
    ObsSquad_Stop
}

api_obssquad_monitoring_0() {
    $HOME/elrond-utils/termui --address localhost:8080
}

api_obssquad_monitoring_1() {
    $HOME/elrond-utils/termui --address localhost:8081
}

api_obssquad_monitoring_2() {
    $HOME/elrond-utils/termui --address localhost:8082
}

api_obssquad_monitoring_3() {
    $HOME/elrond-utils/termui --address localhost:8083
}

api_obssquad_monitoring_proxy() {
    journalctl -f -u elrond-proxy.service
}

#------------------------------------------------------------
#                MultiversX Indexer Commands
#------------------------------------------------------------

api_indexer_start() {
    EsIndexer_Start
}

api_indexer_stop() {
    EsIndexer_Stop
}

#------------------------------------------------------------
#                ElasticSearch and Kibana Commands
#------------------------------------------------------------

api_eskibana_start() {
    EsKibana_Start
}

api_eskibana_stop() {
    EsKibana_Stop
}

#------------------------------------------------------------
#                MultiversX API Commands
#------------------------------------------------------------

api_mx_api_start() {
    MxApi_Start
}

api_mx_api_stop() {
    MxApi_Stop
}

#------------------------------------------------------------
#                   Generic User Configuration
#------------------------------------------------------------

alias ll="ls -lah"
alias ..="cd .."