#
#   This .bashrc part is dedicated to the management of your MultiversX API Services 
#

# Import necessary scripts
source $HOME/mvx-api-deployer/config.cfg
source $HOME/mvx-api-deployer/scripts/0-common.sh
source $HOME/mvx-api-deployer/scripts/5-manage-services.sh

#------------------------------------------------------------
#                Observing Squad Commands
#------------------------------------------------------------

monitoring_0() {
    $HOME/elrond-utils/termui --address localhost:8080
}

monitoring_1() {
    $HOME/elrond-utils/termui --address localhost:8081
}

monitoring_2() {
    $HOME/elrond-utils/termui --address localhost:8082
}

monitoring_3() {
    $HOME/elrond-utils/termui --address localhost:8083
}

monitoring_proxy() {
    journalctl -f -u elrond-proxy.service
}

start_observing_squad() {
    ObsSquad_Start
}

stop_observing_squad() {
    ObsSquad_Stop
}

#------------------------------------------------------------
#                MultiversX Indexer Commands
#------------------------------------------------------------

start_indexer() {
    EsIndexer_Start
}

stop_indexer() {
    EsIndexer_Stop
}

#------------------------------------------------------------
#                ElasticSearch and Kibana Commands
#------------------------------------------------------------

start_es_kibana() {
    EsKibana_Start
}

stop_es_kibana() {
    EsKibana_Stop
}

#------------------------------------------------------------
#                MultiversX API Commands
#------------------------------------------------------------

start_mx_api() {
    MxApi_Start
}

stop_mx_api() {
    MxApi_Stop
}

#------------------------------------------------------------
#                   Generic User Configuration
#------------------------------------------------------------

alias ll="ls -lah"
alias ..="cd .."